"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.extendTypes=exports.typeShape=exports._flatten=exports.toAltSchema=exports.shape=exports.check=exports.verify=void 0;var _slicedToArray=function(){function a(a,b){var c=[],d=!0,e=!1,f=void 0;try{for(var g,h=a[Symbol.iterator]();!(d=(g=h.next()).done)&&(c.push(g.value),!(b&&c.length===b));d=!0);}catch(a){e=!0,f=a}finally{try{!d&&h["return"]&&h["return"]()}finally{if(e)throw f}}return c}return function(b,c){if(Array.isArray(b))return b;if(Symbol.iterator in Object(b))return a(b,c);throw new TypeError("Invalid attempt to destructure non-iterable instance")}}(),_lodash=require("lodash"),_types=require("./types"),_types2=_interopRequireDefault(_types);/**
 * Author: Yusuf Bhabhrawala
 *//* eslint-disable nonblock-statement-body-position *//* eslint-disable no-restricted-syntax *//* eslint-disable no-cond-assign */function _interopRequireDefault(a){return a&&a.__esModule?a:{default:a}}var RX={FLAT_ARRAY:/(\[([^\[\]\{\}]*)\])/,FLAT_OBJECT:/(\{([^\{\}\[\]]*)\})/,MALFORMED:/[\[\]\{\}]/,FLAT_SCALAR:/^[^\[\]\{\}]*$/,OPTIONAL:/^[\?]/,LOOKUP:/^[0-9]+$/,DEFAULTS:/^\$([0-9]+)$/},_flatten=function(a){function b(a){for(var d=void 0,e=!1;(d=a.match(RX.FLAT_ARRAY))||(d=a.match(RX.FLAT_OBJECT));)a=a.substr(0,d.index)+c.length+a.substr(d.index+d[0].length),c.push(d[0]),e=!0;if(e&&b(a),!e&&a.match(RX.MALFORMED))throw"Schema error: probably invalid braces or brackets";return a}// convert "hello world" to $0. remote " (quotes)
for(var c=[],d=[],e=void 0;e=a.match(/"([^"]+)"/);)a=a.substr(0,e.index)+("$"+d.length)+a.substr(e.index+e[0].length),d.push(e[1]);if(a.match(/"/))throw"Missing closing quote";// strip all white spaces
return a=a.replace(/\s/g,""),a=b(a),[a,c,d]};function splitOnce(a,b){var c=a.split(b),d=c.shift();return[d,c.join(b)]}// Set leaf types to format "optional:type:default_value" tuple. Eg. "?:boolean:false" or ":integer:"
var typeShape=function(a){function b(a){if(!a)return"";var c;if(a.match(RX.LOOKUP))return b(f[1*a]);if(c=a.match(RX.FLAT_ARRAY)){a=c[2];var j=a.split(",");return 0<j.length?[b(j[0])]:[b("")]}if(c=a.match(RX.FLAT_OBJECT))return a=c[2],a.split(",").reduce(function(a,c){var d=splitOnce(c,":"),e=_slicedToArray(d,2),f=e[0],g=e[1];return a[f]=b(g),a},{});if(a.match(RX.FLAT_SCALAR)){var d=a.split(":"),e=_slicedToArray(d,2),h=e[0],i=e[1];i||(i=""),i&&i.match(RX.DEFAULTS)&&(i=g[1*i.substr(1)]);var k="";h.match(RX.OPTIONAL)&&(k="?",h=h.substr(1));var l={i:"integer",n:"number",b:"boolean",s:"string"};return l[h]&&(h=l[h]),[k,h,i].join(":")}}var c=_flatten(a),d=_slicedToArray(c,3),e=d[0],f=d[1],g=d[2];return b(e)},toAltSchema=function(a){function b(a){var c=_types2.default.toSchema(a);if("array"===c){var d=0<a.length?b(a[0]):"";return"["+d+"]"}return"object"===c?"{"+Object.keys(a).map(function(c){return c+":"+b(a[c])}).join(",")+"}":c}return b(a)},shape=function(a,b){// flat validator value = {k:t:d,..} [t:d,..] t:d
function c(a){var b=a.value,e=a.schema;e||(e="");var g=void 0,h=!1;// if lookup, validate further
if(e.match(RX.OPTIONAL)&&(e=e.substr(1),h=!0),g=e.match(RX.LOOKUP))return c({value:b,schema:""+(h?"?":"")+f[1*e]});if((null===b||void 0===b)&&h&&!d._optional)return null;if(e.match(RX.FLAT_SCALAR)){// if scalar
var i=void 0,l=void 0,n=e.split(":"),o=_slicedToArray(n,2);return i=o[0],l=o[1],j(i,b,l)}if(g=e.match(RX.FLAT_ARRAY)){e=g[2];var r=e.split(",");return(0,_lodash.isArray)(b)||(b=r.map(function(){return null})),b.length<r.length&&(b=b.concat(r.slice(b.length).map(function(){return null}))),b.map(function(a,b){return c({value:a,schema:r[b%r.length]})})}if(g=e.match(RX.FLAT_OBJECT)){if((!(0,_lodash.isObject)(b)||(0,_lodash.isArray)(b))&&(b={}),e=g[2],""===e)return b;var p=!1,q=e.split(",").reduce(function(a,e){var f=e.split(":"),g=_slicedToArray(f,3),h=g[0],i=g[1],j=g[2];return i||(i=""),j&&(i+=":"+j),"*"===h?p=i:a[h]=c({value:b[h],schema:i}),a},{});if(!1!==p)for(var s in b)void 0===q[s]&&(q[s]=c({value:b[s],schema:p}));return q}}var d=2<arguments.length&&arguments[2]!==void 0?arguments[2]:{},e=new _types2.default(d);d._optional=d._optional||!1;var f=void 0,g=void 0,h=_flatten(b),i=_slicedToArray(h,3);b=i[0],f=i[1],g=i[2];var j=function(a,b,c){var d;return c&&(d=c.match(RX.DEFAULTS))&&(c=g[1*d[1]]),e.has(a)?b&&e.check(a,b)?b:void 0===c?e.sample(a):c:b||c||"Not defined!"},k=c({value:a,schema:b});return k},verify=function(a,b){//console.log("lookups", lookups);
// flat validator value = {k:t:d,..} [t:d,..] t:d
function c(b){var d=b.path,g=b.value,j=b.schema,l=b.parent,n=void 0===l?null:l,o=void 0,p=!1;//console.log("validate", value, schema);
if(j.match(RX.OPTIONAL)){if(j=j.substr(1),void 0===g||null===g)return!0;p=!0}// if lookup, validate further
if(o=j.match(RX.LOOKUP))return c({path:""+d,value:g,schema:""+(p?"?":"")+h[1*j],parent:n});if(j.match(RX.FLAT_SCALAR)){// if scalar
var q=void 0,r=j.split(":"),s=_slicedToArray(r,2);if(j=s[0],q=s[1],void 0===g||null===g)return f.push(d+": is required"),!1;if(""===j)return!0;// no validation needed
if(!e.has(j))throw"Schema error: Validator - "+j+" - not found";else return!!e.check(j,g,{path:d,json:a,parent:n})||(f.push(d+": validation failed"),!1)}else if(o=j.match(RX.FLAT_ARRAY)){// if array
if(!(0,_lodash.isArray)(g))return f.push(d+": should be array"),!1;j=o[2];var t=j.split(",");for(var u in g)c({path:d+"."+u,value:g[u],schema:t[u%t.length],parent:g})}else if(o=j.match(RX.FLAT_OBJECT)){// if object
if(!(0,_lodash.isObject)(g)||(0,_lodash.isArray)(g))return f.push(d+": should be object"),!1;j=o[2];var i=!1;if(""!==j){var v=j.split(",").reduce(function(a,b){var c=b.split(":"),d=_slicedToArray(c,2),e=d[0],f=d[1];return f||(f=""),"*"===e?i=f:a[e]=f,a},{});if(!1!==i)for(var w in g)void 0===v[w]&&(v[w]=i);// if object, validate for all k-v
for(var k in v)c({path:d+"."+k,value:g[k],schema:v[k],parent:g})}}}var d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{},e=new _types2.default(d),f=[],g=d._path||"json",h=void 0,i=_flatten(b),j=_slicedToArray(i,2);if(b=j[0],h=j[1],c({path:g,value:a,schema:b}),0<f.length)throw f.join(", ");return!0},check=function(a,b){try{return verify(a,b),!0}catch(a){if(a.match(/^Schema error/))throw a;return!1}},extendTypes=function(a){_types2.default.extend(a)};// same as verify. returns boolean. won't throw.
exports.verify=verify,exports.check=check,exports.shape=shape,exports.toAltSchema=toAltSchema,exports._flatten=_flatten,exports.typeShape=typeShape,exports.extendTypes=extendTypes;